### ISSUE TITLE
Why is no re-basing done ?

### ISSUE THREAD

**Issue by SkybuckFlying** [Potherca/git-split-file#4]
Hello,

I tried this tutorial, manually by following it exactly, by creating branches, and labels via tag command and then committing, so far seems to work.

I think your script uses a similiar approach, however your script does not seem to use re-base command, is this correct, if so why does your script not do re-base ? Is it not necessary ?

I noticed it used merge instead ? Hmmmm... maybe to keep history ? Yes that was what this was about isn't it this script.

I do believe in keeping history though.... though will it still work well without re-basing hmmm... well interesting your technique offers perhaps a different way of splitting files.

So apperently two techniques exist:
branch
rename
re-base

or
branch
rename
merge

Interesting anyway link is here:

https://stackoverflow.com/questions/3491270/git-merge-apply-changes-to-code-that-moved-to-a-different-file

Maybe your script can also benefit from re-base and offer some interesting future but I guess that goes against the purpose of this script to preserve the history ! May have to try the merge strategy manually see if that can work too... perhaps the real magic is in the "branch and rename" part ! ;) Think so ;)

**Comment by Potherca** [comment]
> why does your script not do re-base ? Is it not necessary ?

It isn't needed for the regular use of this script. If re-running the script were implemented it would also not really work, because of the way the commits are structured (across separate branches).

The merge commit is indeed done to keep the history. It separates the changes in a way that forces git to interpret them as being separate changes. Otherwise, as you point out, history will get lost.

As I stated in issue #3, (and as you suggest in this issue) it might be worth the effort to clean up the existing code so a new feature can be added that would allow a form of rebasing. It wouldn't actually _use_ `git rebase`, it would have to rewind by itself but part of the lower level plumbing could definitely be used.
